/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wiiusej_WiiUseApi */

#ifndef _Included_wiiusej_WiiUseApi
#define _Included_wiiusej_WiiUseApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wiiusej_WiiUseApi
 * Method:    activateSpeaker
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_wiiusej_WiiUseApi_activateSpeaker
  (JNIEnv *, jobject, jint);

/*
 * Class:     wiiusej_WiiUseApi
 * Method:    deactivateSpeaker
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_wiiusej_WiiUseApi_deactivateSpeaker
  (JNIEnv *, jobject, jint);

/*
 * Class:     wiiusej_WiiUseApi
 * Method:    setSpeakerVolume
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_wiiusej_WiiUseApi_setSpeakerVolume
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     wiiusej_WiiUseApi
 * Method:    setSpeakerFrequency
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_wiiusej_WiiUseApi_setSpeakerFrequency
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     wiiusej_WiiUseApi
 * Method:    streamSpeakerData
 * Signature: (I[S)V
 */
JNIEXPORT void JNICALL Java_wiiusej_WiiUseApi_streamSpeakerData
  (JNIEnv *, jobject, jint, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
